# Generated by Django 3.2.7 on 2021-09-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='yoqilgi',
            field=models.CharField(choices=[('Gaz', 'Gaz'), ('Benzin', 'Benzin'), ('Salyarka', 'Salyarka')], default='Bezin', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='persons',
            field=models.PositiveIntegerField(choices=[(1, 'Gaz'), (2, 'Benzin')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='taste',
            field=models.PositiveIntegerField(choices=[(1, 'Gaz'), (2, 'Benzin')]),
        ),
    ]
