# Generated by Django 3.2.7 on 2021-09-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210914_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='yoqilgi',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='persons',
            field=models.CharField(choices=[('Avtomat', 'Avtomat'), ('Ruchnoy', 'Ruchnoy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='taste',
            field=models.CharField(choices=[('Gaz', 'Gaz'), ('Benzin', 'Benzin'), ('Salyarka', 'Salyarka')], max_length=20),
        ),
    ]
