# Generated by Django 3.2.7 on 2021-09-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20210914_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phone_number',
        ),
    ]
