# Generated by Django 3.2.7 on 2021-09-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
