# Generated by Django 3.2.7 on 2021-09-15 07:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0008_restaurant_tel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='CarSell',
        ),
    ]
